# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SPA_binary <- function(mu, g, q, qinv, pval_noadj, tol, maxiter, logp) {
    .Call('_SPA_SPA_binary', PACKAGE = 'SPA', mu, g, q, qinv, pval_noadj, tol, maxiter, logp)
}

